### ISSUE TITLE
2017

### ISSUE THREAD

**Issue by tannewt** [jsaponara/opentaxforms#10]
This project is awesome!

I started fixing things for the 2017 1040 in my repo: https://github.com/tannewt/opentaxforms

Looks like we may need to tune the pdf extraction so that it chunks text a bit more. Some of the form references are looking in in long blocks like:

```
if: if your spouse itemizes on a separate return or you were a dual-status alien,  check here 
▶itemized deductions (from schedule a) or your standard deduction (see left margin) subtract line 
40 from line 38 .exemptions. if line 38 is $156,900 or less, multiply $4,050 by the number on line 
6d. otherwise, see instructionstaxable income.  subtract line 42 from line 41. if line 42 is more than 
line 41, enter -0- tax  (see instructions). check if any from: a alternative minimum tax  (see 
instructions). attach form 6251 ...excess advance premium tax credit repayment. attach form 8962 
.add lines 44, 45, and 46 ..48 foreign tax credit. attach form 1116 if required .49 credit for child and 
dependent care expenses. attach form 2441 50 education credits from form 8863, line 19 51 
retirement savings contributions credit. attach form 8880 52 child tax credit. attach schedule 8812, 
if required.53residential energy credit. attach form 5695..8801 54other credits from form: a add 
lines 48 through 54. these are your total credits ....subtract line 55 from line 47. if line 55 is more 
than line 47, enter -0- ..self-employment tax. attach schedule se ..unreported social security and 
medicare tax from form: a 8919 4137 additional tax on iras, other qualified retirement plans, etc. 
attach form 5329 if required ...
```

I'd love to see this become an Electron app with the IRS forms side-by-side with the instructions.

**Comment by jsaponara** [comment]
Thanks tannewt!  Some of those long blocks of text are related to the way I traverse the tree of pdf objects: textboxes contain textlines which contain text characters, and each level contains all the text of its children.  Certainly I'll look into cleaning up my output though.
Thanks for your work on the 2017 forms, I looked thru your repo.  The main problem turned out to be the jump to a newer version of the xfa [an xml dialect embedded in the forms] format.  The version number is part of the namespace, so having the wrong version number caused many parsing errors.  This is fixed in a recent commit [5c2fab on 09march] but not yet in an official release, which I am working towards.
Thanks for your comments [here and in your repo], they got me moving!

**Comment by jsaponara** [comment]
Also note that the [inadequate] error metrics have improved quite a bit from [2016](https://opentaxforms.org/pages/status-form-1040-family-and-immediate-references-2016.html) to [2017](https://opentaxforms.org/pages/status-form-1040-family-and-immediate-references-2017.html), suggesting that format uniformity has increased.
